{{- $chartName := .Chart.Name -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $chartName }}
  labels:
    app: {{ $chartName }}-app
  namespace: {{ .Values.cluster.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ $chartName }}-app
  template:
    metadata:
      labels:
        app: {{ $chartName }}-app
    spec:
      hostname: {{ $chartName }}

      {{- if .Values.deploy.initContainers }}
      initContainers:
        {{- range .Values.deploy.initContainers }}
        - name: init-{{ .dockerImage.address }}-container
          image: "{{ .dockerImage.address }}:{{ .dockerImage.version }}"
          command:
          {- if .dockerImage.commands }}
          {{- range .dockerImage.commands }}
          - {{ .command }}
          {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}

      containers:
      - args:
        {{- if .Values.deploy.args  }}
        {{- range .Values.deploy.args }}
        - --{{ .key }}={{ .value }}
        {{- end -}}
        {{- end }}
        command:
        {{- if .Values.deploy.cmds }}
        {{- range .Values.deploy.cmds }}
        - {{ .cmd }}
        {{- end }}
        {{- end }}
        name: {{ $chartName }}-container
        {{ if .Values.docker.image.version }}
        image: "{{ .Values.docker.image.address }}:{{ .Values.docker.image.version }}"
        {{ else }}
        image: {{ .Values.docker.image.address | quote }}
        {{ end }}
        imagePullPolicy: {{ .Values.docker.image.imagePullPolicy | default "IfNotPresent" }}
        {{- if .Values.deploy.volumes }}
        volumeMounts:
        {{- range .Values.deploy.volumes }}
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- if .Values.deploy.containerPort }}
        ports:
        - containerPort: {{ .Values.deploy.containerPort }}
        {{- end }}
        {{- if .Values.deploy.envs }}
        env:
        {{- range .Values.deploy.envs }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.deploy.resources }}
        resources:
          limits:
            memory: {{ .Values.deploy.resources.limits.memory | default "256Mi" }}
            {{- if .Values.deploy.resources.limits.cpu }}
            cpu: {{ .Values.deploy.resources.limits.cpu }}
            {{- end }}
          requests:
            memory: {{ .Values.deploy.resources.requests.memory | default "128Mi" }}
            {{- if .Values.deploy.resources.requests.cpu }}
            cpu: {{ .Values.deploy.resources.requests.cpu }}
            {{- end }}
        {{- end }}
        
      {{- if .Values.deploy.tolerations }}
      tolerations:
      - key: {{ .Values.deploy.tolerations.key }}
        operator: {{ .Values.deploy.tolerations.operator | default "Equal" | quote }}
        value: {{ .Values.deploy.tolerations.value | quote }}
        effect: {{ .Values.deploy.tolerations.effect | default "NoSchedule" }}
      {{- end }}

      {{- if .Values.deploy.volumes }}
      volumes:
      {{- range .Values.deploy.volumes }}
      - name: {{ .name }}
        {{- if .pv }}
        persistentVolumeClaim:
          claimName: {{ $chartName }}-pvc
        {{- else if .configMap }}
        configMap:
          name: {{ $chartName }}-config
          {{- if .items }}
          items:
          {{- range .items }}
          - key: {{ .key }}
            path: {{ .path }}
          {{- end }}
          {{- end }}
        {{- else }}
        hostPath:
          path: {{ .path }}
          type: {{ .type }}
        {{- end }}
      {{- end }}
      {{- end }}

